# Generated by Django 4.1.3 on 2022-11-23 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cropper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="images",
            old_name="full_hog",
            new_name="image_embeddings_background_image",
        ),
        migrations.RenameField(
            model_name="images",
            old_name="half_hog",
            new_name="image_embeddings_full_image",
        ),
    ]
